model:
  name: "lvwerra/gpt2-imdb"
  load_in_8bit: false
  peft_model_id: null
  torch_dtype: null # fp16/null
  device_map: cuda:0
  padding_side: right
seed: 42
batch_size: 16
data:
  dataset_name: ./data/raw/train_2286.csv
  max_prompt_length: 32
  prompt_column: "text"  
generate_config:
  temperature: 0.7
  do_sample: true
  max_new_tokens: 256
  no_repeat_ngram_size: 2
  top_k: 40
  use_cache: true
  num_return_sequences: 8
log_config:
  save_steps: 5
  dir: ./data/intermediate
  file_name: sft_N_response.csv